app/models.py
from datetime import datetime
from . import db 
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,  primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    pass_secure = db.Column(db.String(255))

    pitchs = db.relationship('Pitch',backref='user',lazy='dynamic')
    comments = db.relationship('Comment', backref = 'comment', lazy= "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'


class Subscriber(db.Model):
    __tablename__ = 'subscribers'
    id = db.Column(db.Integer,primary_key = True)
    subscriber_name = db.Column(db.String(50))
    subscriber_email = db.Column(db.String(255), unique = True)         

class Pitch(db.Model):
    __tablename__ = 'pitch'

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    content = db.Column(db.String())
    category = db.Column(db.String(255))
    
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    pitch_id = db.relationship('Comment', backref = 'comments', lazy= "dynamic")

    @classmethod
    def get_pitches(cls, category):
        pitches = Pitch.query.filter_by(pitch_category=category).all()
        return pitches

    def __repr__(self):
        return f'{self.title}'

class Comment(db.Model):
    __tablename__='comments'

    id = db.Column(db.Integer,primary_key=True)
    comment_content = db.Column(db.String())
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitch.id'))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

   


    def __repr__(self):
        return f'{self.comment}' 

        

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import Required,Email
from wtforms import StringField, TextAreaField, SubmitField, SelectField

class PitchForm(FlaskForm):

    title = StringField('Pitch title')
    category= SelectField('Pitch Category', choices=[('Select a category', 'Select a category'),('Business', 'Business'),('Science and Tech', 'Science and Tech'),('Interview Pitch', 'Interview Pitch'),('Maths pitch', 'Maths pitch'),('Pick-up lines', 'Pick-up lines')])
    content = TextAreaField('The pitch...')
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = TextAreaField('Post Of The Comment')
    submit = SubmitField('Submit')

class SubscribeForm(FlaskForm):
    subscriber_name = StringField('Enter your Full Name',validators=[Required()])
    subscriber_email = StringField('Enter your Email',validators=[Required(),Email()])
    submit = SubmitField('Subscribe') 

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager 
from flask_mail import Mail


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()

bootstrap = Bootstrap()

db = SQLAlchemy()
# def new_func():
#     photos = UploadSet('photos',IMAGES)
#     return photos

# photos = new_func()

def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    db.init_app(app)
    bootstrap = Bootstrap(app)
    login_manager.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure_uploads(app,photos)

    return app 

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import Flask
from . import main
from flask_login import login_required
from flask import render_template, redirect, url_for,flash
import datetime
from ..models import Pitch, Comment,Subscriber,User
from .forms import PitchForm , CommentForm,SubscribeForm
from .. import db

app = Flask(__name__)


@main.route("/")
def index():
   '''
   title = "Bensam blog"
   '''
  
   title = 'Bensam blog'
   pitch=Pitch.query.order_by(Pitch.id.desc()).all()

   return render_template('index.html', title = title,pitch = pitch,)

@main.route('/pitch/new', methods=['GET','POST'])
@login_required
def new_pitch():
    form = PitchForm()

    if form.validate_on_submit():

        title=form.title.data
        content=form.content.data
        category=form.category.data
        pitch = Pitch(title=title, content=content,category=category)
        db.session.add(pitch)
        db.session.commit()

        flash('Your was a success!', 'success')
        return redirect(url_for('main.index', id=pitch.id))

    return render_template('pitches.html', title='New Post', pitch_form=form, post ='New Post') 

@main.route('/subscription',methods=['GET','POST'])
def subscription():
    subscription_form = SubscribeForm()

    if subscription_form.validate_on_submit():
        new_subscriber = Subscriber(subscriber_name=subscription_form.subscriber_name.data,subscriber_email=subscription_form.subscriber_email.data)

        db.session.add(new_subscriber)
        db.session.commit()

        return redirect(url_for('main.index'))    

    return render_template('subscription.html',subscription_form = subscription_form)     


@main.route('/comment/new/<int:id>', methods=['GET','POST'])
@login_required
def new_comment(id):
    form = CommentForm()

    if form.validate_on_submit():
        
        comment_content = form.comment.data
        

        comment = Comment(comment_content= comment_content,pitch_id=id)

        db.session.add(comment)
        db.session.commit()
        
    comment = Comment.query.filter_by(pitch_id=id).all()
  


    return render_template('coments.html', title='New Post', comment=comment,comment_form=form, post ='New Post')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bensam blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
    crossorigin="anonymous">
</head>

<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Bensam <b>BLOG</b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
    
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">log out</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">login</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.register')}}" class="btn btn-outline-success">Sign up</a>
              </li>
              <li class="nav-item">
              <a href="{{ url_for('main.new_pitch') }}"><button style="color: rgb(255, 255, 255);" class="btn btn-success">Create a blog</button></a>
              </li>
            </ul>
            {% if current_user.is_authenticated %}
            <span class="navbar-text">
              Welcome <em style="color: white;">{{ current_user.username }}  </em>
            </span>
            {% endif %}
          </div>
        </div>
      </nav>
      {% endblock navbar %}


{% block content %}

{% endblock %}

{% block footer %}
<footer>
<div class="navbar navbar-expand-lg navbar-dark bg-dark" style="color: white;justify-content: center;">
        <a class="nav-link active" aria-current="page" style="color: white;" href="/">Copyright 2021|bensam</a>
</div>
</footer>
{% endblock%}
    
</body>
<style>
  body{
    background-image: url("../static/bg.jpg");
    background-repeat: no-repeat;
    background-size: cover;
  }
</style>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" 
integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" 
integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
</script>

</html>

app/templates/coments.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container" style="background-color: #04CED5; height: fit-content;margin-top: 100px;">
    <div id="login-row" class="row justify-content-center align-items-center">
        <div id="login-column" class="col-md-6">
            <div class="box">
                <div class="float" style="margin-bottom: 40px; margin-top: 40px;background-color:#01a3a8;padding: 20px;border-radius: 20px; color: white;">
                    <div class="card-header"><h1>We Value your comment</h1></div>
                    <br><br>
                    {{ wtf.quick_form(comment_form) }}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- ===================================================================== -->
<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<div class="container" style="margin-top: 20px;">
    <div class="row" style="justify-content: space-evenly;">
        {% for comment in comment%}
        <div class="card" style="width: 25rem;">
            <div class="card-header">
                Comment {{ comment.username }}
            </div>
            <div class="card-body">
            <h5 class="card-title">Comment {{ comment.username }}</h5>
            <p class="card-text"> {{comment.comment_content}}</p>
            <a href="#"><button class="btn btn-outline-success btn-sm like">like</button></a>
            <a href="#"><button class="btn btn-outline-warning btn-sm dislike">dislike</button></a>
            </div>
        </div>
        {% endfor %}
   </div>
</div>

{% endblock%}

app/templates/fourowfour.html
<h1>Sorry does not exist</h1>

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html'as macros %}
{% block styles%}
    {{ super() }}
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    {% endblock %}
    <body>
    {% block content %}
<div class="container-fluid" style="background-color: rgba(0, 0, 0, 0.637);
padding: 50px;min-height: 100vh;">
            <br>
            <br>
            <div class="row">
                        {{macros.displayPitches(pitch)}}
            </div>

                <div class="row">
                    <div class="card" style="width: 25rem;">
                        <div class="card-header">
                          Featured
                        </div>
                        <div class="card-body">
                          <h5 class="card-title">Special title treatment</h5>
                          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                          <a href="#"><button class="btn btn-outline-success btn-sm like">like</button></a>
                          <a href="#"><button class="btn btn-outline-warning btn-sm dislike">dislike</button></a>
                          <a href="#" class="btn btn-outline-warning btn-sm" id="comment">comment</a>
                        </div>
                      </div>
                      <div class="card" style="width: 25rem;">
                        <div class="card-header">
                          Featured
                        </div>
                        <div class="card-body">
                          <h5 class="card-title">Special title treatment</h5>
                          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                          <a href="#"><button class="btn btn-outline-success btn-sm like">like</button></a>
                          <a href="#"><button class="btn btn-outline-warning btn-sm dislike">dislike</button></a>
                          <a href="#" class="btn btn-outline-warning btn-sm" id="comment">comment</a>
                        </div>
                      </div>

                      <div class="card" style="width: 25rem;">
                        <div class="card-header">
                          Featured
                        </div>
                        <div class="card-body">
                          <h5 class="card-title">Special title treatment</h5>
                          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                          <a href="#"><button class="btn btn-outline-success btn-sm like">like</button></a>
                          <a href="#"><button class="btn btn-outline-warning btn-sm dislike">dislike</button></a>
                          <a href="#" class="btn btn-outline-warning btn-sm" id="comment">comment</a>
                        </div>
                      </div>

                      <div class="card" style="width: 25rem;">
                        <div class="card-header">
                          Featured
                        </div>
                        <div class="card-body">
                          <h5 class="card-title">Special title treatment</h5>
                          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                          <a href="#"><button class="btn btn-outline-success btn-sm like">like</button></a>
                          <a href="#"><button class="btn btn-outline-warning btn-sm dislike">dislike</button></a>
                          <a href="#" class="btn btn-outline-warning btn-sm" id="comment">comment</a>
                        </div>
                      </div>
                    
                </div>   
</div>  
<style>
    .row{
        display: flex;
        justify-content: space-evenly;
    }
</style>
<script type="text/javascript">
$(document).ready(function(){
    var like=0
    var dislike=0
    $(".like").click(function(){
        like++;
        document.getElementsByClassName("like").innerHTML="like" + like

});
$(".dislike").click(function(){
        dislike++;
        document.getElementById("mane").innerHTML="dislike" + dislike

});
    
})

</script>
{% endblock  %}

app/templates/macros.html
{% macro displayPitches(list) %}
{% for pitch in list %}
<div class="card" style="width: 25rem;">
    <div class="card-header">
        Category: {{ pitch.category }}
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ pitch.title }}</h5>
      <p class="card-text"> {{ pitch.content }}</p>
      <a href="#"><button class="btn btn-outline-success btn-sm like">like</button></a>
      <a href="#"><button class="btn btn-outline-warning btn-sm dislike">dislike</button></a>
      <a href="{{ url_for('main.new_comment',id=pitch.id) }}" class="btn btn-outline-warning btn-sm" id="comment">comment</a>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function(){
        var like=0
        var dislike=0
        $("#like").click(function(){
            like++;
            document.getElementById("name").innerHTML=like
    
    });
    $("#dislike").click(function(){
            dislike++;
            document.getElementById("mane").innerHTML=dislike
    
    });
        
    })
    
    </script>

{% endfor %}
{% endmacro %}

app/templates/pitches.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="container" style="background-color: #04CED5; height: fit-content;margin-top: 100px;">
    <div id="login-row" class="row justify-content-center align-items-center">
        <div id="login-column" class="col-md-6">
            <div class="box">
                <div class="float" style="margin-bottom: 40px; margin-top: 100px;background-color:#01a3a8;padding: 20px;border-radius: 20px; color: white;">
                    <div class="card-header"><h1>bensam blog</h1></div>
                    <br><br>
                    {{wtf.quick_form(pitch_form)}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}